### ISSUE TITLE
[Feature Request] Individual control

### ISSUE THREAD

**Issue by Armored-22** [oscarpedrero/Notify#2]
Firstly, thank you for this mod and the work done on it.

The ability for each player to use a command to silence notifications if wanted. 

I personally love it but some people's feedback on the server have been "annoyed" when there is a lot of players on killing V Bloods for example. 

!ignore vbloodannounce for each person who wants to turn it off? Just throwing it out there.

**Comment by oscarpedrero** [comment]
First of all, thanks for your comment!

I would have to look at how that can affect the performance of the server, because in principle it is a system message for everyone who is online, if we activated that, I would have to check which players are online and each player who was not in the deactivated list to send you the specific message.

I explore the possibility and tell you something ;)

**Comment by oscarpedrero** [comment]
@Armored-22 It is already available in the latest version. Thanks for your idea

https://v-rising.thunderstore.io/package/Trodi/Notify/
